version: '3.1'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: wedoogift
      MONGO_INITDB_ROOT_PASSWORD: wedoogift
      MONGO_INITDB_DATABASE: wedoogift


volumes:
  mongo_data: